// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A sustainability tool providing recommendations for improving fishing practices.
 *
 * - sustainabilityTool - A function that provides sustainability recommendations.
 * - SustainabilityToolInput - The input type for the sustainabilityTool function.
 * - SustainabilityToolOutput - The return type for the sustainabilityTool function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SustainabilityToolInputSchema = z.object({
  species: z.string().describe('The species of fish caught.'),
  location: z.string().describe('The location where the fish was caught.'),
  date: z.string().describe('The date when the fish was caught.'),
  method: z.string().describe('The method used to catch the fish.'),
});
export type SustainabilityToolInput = z.infer<typeof SustainabilityToolInputSchema>;

const SustainabilityToolOutputSchema = z.object({
  recommendations: z.string().describe('Recommendations for improving the sustainability of fishing practices based on the provided data.'),
});
export type SustainabilityToolOutput = z.infer<typeof SustainabilityToolOutputSchema>;

export async function sustainabilityTool(input: SustainabilityToolInput): Promise<SustainabilityToolOutput> {
  return sustainabilityToolFlow(input);
}

const sustainabilityToolPrompt = ai.definePrompt({
  name: 'sustainabilityToolPrompt',
  input: {schema: SustainabilityToolInputSchema},
  output: {schema: SustainabilityToolOutputSchema},
  prompt: `You are an expert in sustainable fishing practices.

  Based on the following information about a fishing catch, provide recommendations for improving the sustainability of the fisher's practices.

  Species: {{{species}}}
  Location: {{{location}}}
  Date: {{{date}}}
  Method: {{{method}}}

  Provide specific and actionable recommendations that the fisher can implement to improve their sustainability score for future catches.
  `,
});

const sustainabilityToolFlow = ai.defineFlow(
  {
    name: 'sustainabilityToolFlow',
    inputSchema: SustainabilityToolInputSchema,
    outputSchema: SustainabilityToolOutputSchema,
  },
  async input => {
    const {output} = await sustainabilityToolPrompt(input);
    return output!;
  }
);
