// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Sustainability Scoring AI agent.
 *
 * - sustainabilityScore - A function that calculates the sustainability score of a catch.
 * - SustainabilityScoreInput - The input type for the sustainabilityScore function.
 * - SustainabilityScoreOutput - The return type for the sustainabilityScore function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SustainabilityScoreInputSchema = z.object({
  species: z.string().describe('The species of the catch.'),
  location: z.string().describe('The location of the catch.'),
  date: z.string().describe('The date of the catch (YYYY-MM-DD).'),
  method: z.string().describe('The method used to catch the fish.'),
});

export type SustainabilityScoreInput = z.infer<typeof SustainabilityScoreInputSchema>;

const SustainabilityScoreOutputSchema = z.object({
  score: z.number().describe('The sustainability score of the catch (0-100).'),
  rationale: z.string().describe('The rationale behind the sustainability score.'),
});

export type SustainabilityScoreOutput = z.infer<typeof SustainabilityScoreOutputSchema>;

export async function sustainabilityScore(input: SustainabilityScoreInput): Promise<SustainabilityScoreOutput> {
  return sustainabilityScoreFlow(input);
}

const prompt = ai.definePrompt({
  name: 'sustainabilityScorePrompt',
  input: {schema: SustainabilityScoreInputSchema},
  output: {schema: SustainabilityScoreOutputSchema},
  prompt: `You are an expert in sustainable fishing practices. You will be provided with details about a fish catch, and you will calculate a sustainability score from 0 to 100, where 0 is the least sustainable and 100 is the most sustainable.  You must also provide a rationale for the score.

Catch Details:
Species: {{{species}}}
Location: {{{location}}}
Date: {{{date}}}
Method: {{{method}}}

Respond in JSON format.
`,
});

const sustainabilityScoreFlow = ai.defineFlow(
  {
    name: 'sustainabilityScoreFlow',
    inputSchema: SustainabilityScoreInputSchema,
    outputSchema: SustainabilityScoreOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
